#' @import DBI
#' @import methods
#' @include SASEGS4.R
#' @include SASEGDataType.R
NULL

#' Driver class for SAS Enterprise Guide.
#'
#' @keywords internal
#' @export
setClass("SASEGDriver", contains = "DBIDriver")

#' @export
#' @rdname SASEG-class
setMethod("dbUnloadDriver", "SASEGDriver", function(drv, ...) {
  TRUE
})

setMethod("show", "SASEGDriver", function(object) {
  cat("<SASEGDriver>\n")
})

# SAS EG Class
#' @export
SASEG <- function() {
  new("SASEGDriver")
}


#' SAS class.
#'
#' @export
setClass("SAS", contains = "character")

setGeneric("SAS", function(x, ...) standardGeneric("SAS"))

setMethod("SAS", "character", function(x, ...) {
  new("SAS", x)
})

setMethod("SAS", "SAS", function(x, ...) {
  return(x)
})

setMethod("SAS", "SQL", function(x, ...) {
  new("SAS",
      paste0("PROC SQL DQUOTE=ANSI;\n",
             "ods output SQL_Results=SQLOut;\n",
             x, ";\n",
             "QUIT;\n"))
})

setMethod("show", "SAS", function(object) {
  cat(paste0("<SAS> ", object@.Data, collapse = "\n"))
})


#' SAS EG connection class.
#'
#' @export
#' @keywords internal
setClass("SASEGConnection",
         contains = "DBIConnection",
         slots = list(
           profile = "character",
           server = "character",
           # Slot application is a SAS EG Application object
           application = "SASEGApplication",
           # Slot SASProject is a SAS EG Project object
           SASProject = "SASEGProject",
           SASUtil = "SASEGCode",
           dbms = "character"
         )
)

noteUtil <- SAS(paste0(
  "/* This program was generated by RSASEG package for utilitary purpose. */\n",
  "/* You can delete it. */\n\n"
))

#' @param drv An object created by \code{SASEG()}
#' @rdname SASEG
#' @export
#' @examples
#' \dontrun{
#' db <- dbConnect(RSASEG::SASEG(), DLLFilePath, profile, server, dbms)
#' dbWriteTable(db, "mtcars", mtcars)
#' dbGetQuery(db, "SELECT * FROM mtcars WHERE cyl == 4")
#' }
setMethod("dbConnect", "SASEGDriver", function(drv, DLLFilePath, profile, server, dbms, ...) {
  # Load SAS.EG.Scripting namespace:
  loadSASEGScripting(DLLFilePath)
  # Create a new SAS EG Application object:
  application <- SASEGApplication()
  # Set profile:
  setProfile(application, profile)
  # Create a new SAS EG Project object:
  SASProject <- newProject(application)
  # Create a new SAS EG Code project to run utils tasks (e.g. fetch programs):
  SASUtil <- newCode(project = SASProject, server = server, program = noteUtil, name = "garbage")
  dbms <- NULL
  class(dbms) <- "character"
  new("SASEGConnection", profile = profile, server = server, application = application, SASProject = SASProject, SASUtil = SASUtil, dbms = dbms)
})

setMethod("show", "SASEGConnection", function(object) {
  show(object@application)
  cat(
    "Used Profile in Active Connection: ", object@profile, "\n",
    "SAS Server to Run Programs in Active Connection: ", object@server, "\n",
    "DBMS SQL Pass-Through: ", if(length(object@dbms) == 0) "NONE" else object@dbms,
    sep = ""
    )
})

setMethod("dbDisconnect", "SASEGConnection", function(conn, projectPath = NULL, ...) {
  if(!is.null(projectPath))  saveAs(conn@SASProject, projectPath)
  terminate(conn@application)
  return(TRUE)
  })


#' SASEG results class.
#'
#' @keywords internal
#' @export
setClass("SASEGResult",
         contains = "DBIResult",
         slots = list(SASResult = "SASEGCode", SASUtil = "SASEGCode", fetched = "function", rowsFetched = "function")
         )

# A closure creator
# Example :
# Initialisation:
# state <- state_generator()
# Retrieve value:
# state()
# copy_state <- state
# Change value:
# state(set = TRUE)
# state()
# copy_state()
state_generator <- function(init = FALSE) {
  state <- init
  function(set = NULL) {
    if(is.null(set)) return(state)
    if(!is.logical(set)) return(state)
    state <<- set
  }
}

# A closure creator
# Example :
# Initialisation:
# counter <- count_generator()
# Retrieve value:
# count()
# Change value:
# count(add = 12)
# count()
count_generator <- function(init = 0) {
  count <- init
  function(add = NULL) {
    if(is.null(add)) return(count)
    count <<- round(count + add)
  }
}


setGeneric("setFetched", function(res, value) standardGeneric("setFetched"))
setMethod("setFetched", "SASEGResult", function(res, value) {
  res@fetched(set = value)
})

setMethod("dbHasCompleted", "SASEGResult", function(res, ...) {
  res@fetched()
})


#' Send a query to SAS EG.
#'
#' @export
#' @examples
#' # This is another good place to put examples
setMethod("dbSendQuery", "SASEGConnection", function(conn, statement, codeName = NULL, ...) {
  if(class(statement) %in% c("SAS", "SQL")) {
    program <- SAS(statement)
    # Create a new SAS EG Code object with server and SAS program:
    SASCode <- newCode(conn@SASProject, server = conn@server, program = program, name = codeName)
    # Execute SAS program:
    run(SASCode)
    # Only for debugging:
    #cat(getSourceCode(SASCode))
    res <- new("SASEGResult",
               SASResult = SASCode,
               SASUtil = conn@SASUtil,
               fetched = state_generator(),
               rowsFetched = count_generator())
    if(countOutputDatasets(SASCode) == 0) setFetched(res, value = TRUE)
    return(res)
  } else {
    message("Statement:\n", statement,
            "\nClass: ", class(statement),
            "\nNo query sent to SAS: the query must be an SQL or a SAS class object.",
            "\nTry SAS(", statement, ") or\n",
            "SQL(", statement, ")")
    return(NULL)
    }
})


#' @export
setMethod("dbClearResult", "SASEGResult", function(res, ...) {
  l <- getListDatasets(res@SASResult)
  drop_char <- paste("DROP TABLE", lapply(l, getFileName))
  drop_sql <- lapply(drop_char, SQL)
  drop_sas <- paste(noteUtil, lapply(drop_sql, SAS))
  SASUtil <- res@SASUtil
  i <- 1
  while(i <= length(drop_sas)) {
    setText(SASUtil, drop_sas[[i]])
    run(SASUtil)
    i <- i+1
  }
  return(TRUE)
})


#' Retrieve records from SAS EG query
#' @export
setMethod("dbFetch", "SASEGResult", function(res, n = -1, ...) {
  l <- getListDatasets(res@SASResult)
  if(length(l)>1) stop("Query results contain multiple datasets; cannot execute dbFetch() method.\n  Please run:\n  res <- dbSendQuery(statement)\n  datalist <- dbFetchAll(res)")
  l <- l[[1]]
  path <- saveAs(object = l)
  d <- data.table::fread(path)
  setFetched(res = res, value = TRUE)
  return(d)
})

setGeneric("dbFetchAll", function(res, ...) standardGeneric("dbFetchAll"))
setMethod("dbFetchAll", "SASEGResult", function(res, ...) {
  l <- getListDatasets(res@SASResult)
  n <- length(l)
  d <- vector("list", n)
  i <- 1
  while(i <= length(l)) {
    path <- saveAs(object = l[[i]])
    d[[i]] <- data.table::fread(path)
    i <- i+1
  }
  setFetched(res = res, value = TRUE)
  if(n == 1) {d <- d[[1]]}
  return(d)
})

setGeneric("dbGetLog", function(res, ...) standardGeneric("dbGetLog"))
setMethod("dbGetLog", "SASEGResult", function(res, ...) {
  getLog(res@SASResult)
})

setMethod("dbDataType", "SASEGDriver", function(dbObj, obj, ...) {
  # Ce programme sera à modifier si on veut faire du SAS SQL pass-through
  if(class(obj) %in% names(SASEGDataType)) {
    return(SASEGDataType[[class(obj)]])
  } else {
    return(dbDataType(ANSI(), obj, ...))
  }
})

setMethod("dbDataType", "SASEGConnection", function(dbObj, obj, ...) {
  dbDataType(SASEG(), obj)
})

setMethod("dbQuoteString", c("SASEGConnection", "character"), function(conn, x, ...) {
  # Ce programme sera à modifier si on veut faire du SAS SQL pass-through
  dbQuoteString(ANSI(), x, ...)
})

setMethod("dbQuoteString", c("SASEGConnection", "SQL"), function(conn, x, ...) {
  # Ce programme sera à modifier si on veut faire du SAS SQL pass-through
  dbQuoteString(ANSI(), x, ...)
})

setMethod("dbQuoteIdentifier", c("SASEGConnection", "character"), function(conn, x, ...) {
  # Ce programme sera à modifier si on veut faire du SAS SQL pass-through
  dbQuoteIdentifier(ANSI(), x, ...)
})

setMethod("dbQuoteIdentifier", c("SASEGConnection", "SQL"), function(conn, x, ...) {
  # Ce programme sera à modifier si on veut faire du SAS SQL pass-through
  dbQuoteIdentifier(ANSI(), x, ...)
})

setMethod("dbQuoteIdentifier", c("SASEGConnection", "Table"), function(conn, x, ...) {
  # Ce programme sera à modifier si on veut faire du SAS SQL pass-through
  dbQuoteIdentifier(ANSI(), x, ...)
})

setMethod("dbWriteTable", "SASEGConnection", function(conn, name, value, ...) {
  # Ce programme sera à modifier si on veut faire du SAS SQL pass-through
  program <- SAS(sqlCreateTable(conn, name, value))
  # Create a new SAS EG Code object with server and SAS program:
  SASCode <- newCode(conn@SASProject, server = conn@server, program = program, name = paste("Create Table", name))
  run(SASCode)
})


