#' @importFrom stats runif

noteUtil <- paste0(
  "/* This program was generated by RSASEG package for utilitary purpose. */\n",
  "/* You can delete it. */\n\n"
)

SASMonth <- c("JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC")

is.Date <- function(x) {
  if("Date" %in% class(x)) {
    return(TRUE)
  } else {
    if("AsIs" %in% class(x)) {x <- unclass(x)} 
    return("Date" %in% class(x))  
  }
}

is.DateTime <- function(x) {
  if("POSIXt" %in% class(x)) {
    return(TRUE)
  } else {
    if("AsIs" %in% class(x)) {x <- unclass(x)} 
    return("POSIXt" %in% class(x))  
  }
}

is.difftime <- function(x) {
  if("difftime" %in% class(x)) {
    return(TRUE)
  } else {
    if("difftime" %in% class(x)) {x <- unclass(x)} 
    return("difftime" %in% class(x))  
  }
}

# Return a SAS Date constant from a Date
SASDateConstant <- function(x) {
  if(is.null(x)) return(NULL)
  if(is.na(x)) return(NA_character_)
  paste0("'", format(x, "%d"), SASMonth[as.integer(format(x, "%m"))], format(x, "%Y"), "'d")
}

# Return a SAS Datetime constant from a POSIXct
SASDateTimeConstant <- function(x) {
  if(is.null(x)) return(NULL)
  if(is.na(x)) return(NA_character_)
  paste0("'", 
         format(x, "%d"), 
         SASMonth[as.integer(format(x, "%m"))], 
         format(x, "%Y"),
         ":",
         format(x, "%H"),
         ":",
         format(x, "%M"),
         ":",
         format(x, "%S"),
         "'dt")
}

# Return a SAS Time constant from a difftime
SASTimeConstant <- function(x, unit) {
  if(is.null(x)) return(NULL)
  if(is.na(x)) return(NA_character_)
  x <- as.difftime(x, unit = unit)
  units(x) <- "hours"
  if(x >= 100) warning("A difftime is greater or equal than 100 hours: values returned by SAS will be false.", immediate. = TRUE)
  h <- as.character(floor(x))
  if(nchar(h) == 1) {h <- paste0("0", h)}
  x <- x-floor(x)
  units(x) <- "mins"
  m <- as.character(floor(x))
  if(nchar(m) == 1) {m <- paste0("0", m)}
  x <- x-floor(x)
  units(x) <- "secs"
  s <- as.character(round(x))
  if(nchar(s) == 1) {s <- paste0("0", s)}
  paste0("'", h, ":", m, ":", s, "'t")
}


# A closure creator
# Example :
# Initialisation:
# state <- state_generator()
# Retrieve value:
# state()
# copy_state <- state
# Change value:
# state(set = TRUE)
# state()
# copy_state()
state_generator <- function(init = FALSE) {
  state <- init
  function(set = NULL) {
    if(is.null(set)) return(state)
    if(!is.logical(set)) return(state)
    state <<- set
  }
}

# A closure creator
# Example :
# Initialisation:
# counter <- count_generator()
# Retrieve value:
# count()
# Change value:
# count(add = 12)
# count()
count_generator <- function(init = 0) {
  count <- init
  function(add = NULL) {
    if(is.null(add)) return(count)
    count <<- round(count + add)
  }
}

cnx_list_generator <- function(init = NULL) {
  cnx <- init
  list(
    get = function() if(is.null(cnx)) return(list()) else return(list(cnx)),
    set = function(obj) {
      if(is.null(obj)) {
        cnx <<- obj
      } else {
        stopifnot("SASEGConnection" %in% class(obj), is.null(cnx))
        cnx <<- obj
      }
    }
    )
}

random_table_name <- function(n = 28) {
  paste0(LETTERS[ceiling(stats::runif(n, min = 0, max = 26))], collapse = "")
  }