noteUtil <- paste0(
  "/* This program was generated by RSASEG package for utilitary purpose. */\n",
  "/* You can delete it. */\n\n"
)

SASMonth <- c("JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC")

is.Date <- function(x) {
  if("AsIs" %in% class(x)) {x <- unclass(x)}
  return("Date" %in% class(x))
}

is.DateTime <- function(x) {
  if("AsIs" %in% class(x)) {x <- unclass(x)}
  return("POSIXt" %in% class(x))
}

# Return a SAS Date constant from a Date
SASDateConstant <- function(x) {
  if(is.null(x)) return(NULL)
  if(is.na(x)) return(NA_character_)
  paste0("'", format(x, "%d"), SASMonth[as.integer(format(x, "%m"))], format(x, "%Y"), "'d")
}

# Return a SAS Datetime constant from a POSIXct
SASDateTimeConstant <- function(x) {
  if(is.null(x)) return(NULL)
  if(is.na(x)) return(NA_character_)
  paste0("'", 
         format(x, "%d"), 
         SASMonth[as.integer(format(x, "%m"))], 
         format(x, "%Y"),
         ":",
         format(x, "%H"),
         ":",
         format(x, "%M"),
         ":",
         format(x, "%S"),
         "'dt")
}

# A closure creator
# Example :
# Initialisation:
# state <- state_generator()
# Retrieve value:
# state()
# copy_state <- state
# Change value:
# state(set = TRUE)
# state()
# copy_state()
state_generator <- function(init = FALSE) {
  state <- init
  function(set = NULL) {
    if(is.null(set)) return(state)
    if(!is.logical(set)) return(state)
    state <<- set
  }
}

# A closure creator
# Example :
# Initialisation:
# counter <- count_generator()
# Retrieve value:
# count()
# Change value:
# count(add = 12)
# count()
count_generator <- function(init = 0) {
  count <- init
  function(add = NULL) {
    if(is.null(add)) return(count)
    count <<- round(count + add)
  }
}

random_table_name <- function(n = 28) {
  paste0(LETTERS[ceiling(runif(n, min = 0, max = 26))], collapse = "")
  }