noteUtil <- paste0(
  "/* This program was generated by RSASEG package for utilitary purpose. */\n",
  "/* You can delete it. */\n\n"
)

# A closure creator
# Example :
# Initialisation:
# state <- state_generator()
# Retrieve value:
# state()
# copy_state <- state
# Change value:
# state(set = TRUE)
# state()
# copy_state()
state_generator <- function(init = FALSE) {
  state <- init
  function(set = NULL) {
    if(is.null(set)) return(state)
    if(!is.logical(set)) return(state)
    state <<- set
  }
}

# A closure creator
# Example :
# Initialisation:
# counter <- count_generator()
# Retrieve value:
# count()
# Change value:
# count(add = 12)
# count()
count_generator <- function(init = 0) {
  count <- init
  function(add = NULL) {
    if(is.null(add)) return(count)
    count <<- round(count + add)
  }
}

